### PR TITLE
Fixed a bug

### PR DESCRIPTION
**Pull request by sungjuly**
Thanks for making wrapper of WebHDFS API.
This change is very simple bug fix, please merge this PR if you want.

### CODE REVIEW

**Comment by fasouto** [comment]
Thanks for this @sungjuly , I don't know how I can miss such a simple bug. I guess that hdfs when no user is provided is getting the value of $USER

**Comment by sungjuly** [comment]
@fasouto is there any release plan? It would be great if you release this to PIP. ;)

**Comment by fasouto** [comment]
Sure, I'll upload it this afternoon when I got home. Thanks for the heads up!

**Comment by fasouto** [comment]
@sungjuly latest version 0.3.5 it's now on pip

**Pull request merged**
